name: hainong
description: Dam Ca Mau
publish_to: 'none'
version: 1.0.60+89
environment:
  sdk: ">=2.16.0 <3.0.0"

dependency_overrides:
  connectivity_plus: 2.3.9
  dart_webrtc: 1.0.12
  device_info_plus: 4.0.0
  file_picker:
    path: modules/file_picker-4.6.1
  firebase_auth_platform_interface: 6.3.2
  firebase_core_platform_interface: 4.5.3
  firebase_dynamic_links: 4.3.11
  ffi: 2.0.1
  flutter_inappwebview: 6.0.0-beta.28
  geolocator_android: 4.1.7
  image: ^4.0.6
  image_picker: 0.8.4
  intl: 0.18.0
  meta: 1.8.0
  photo_manager: 2.8.2
  youtube_player_flutter:
    path: modules/youtube_player_flutter
  url_launcher: 6.1.0

dependencies:
  flutter:
    sdk: flutter
  html_editor_enhanced:
    path: modules/html_editor_enhanced-2.4.0
  zalo_flutter:
    path: modules/zalo_flutter-0.0.5

  advn_video: 0.0.18
  calendar_date_picker2: ^1.0.6
  carousel_slider: ^4.1.1
  cupertino_icons: 1.0.5
  dotted_border: ^2.0.0
  dropdown_button2: ^2.3.9
  expandable: 5.0.1
  firebase_analytics: 9.1.0
  firebase_auth: 3.3.8
  firebase_core: 1.20.0
  firebase_messaging: 12.0.0
  floating_draggable_advn: 1.0.6
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: 5.0.7
  flutter_html: 3.0.0-alpha.5
  flutter_local_notifications: 9.9.1
  flutter_screenutil: 5.0.3
  flutter_staggered_grid_view: 0.6.0
  geolocator: 9.0.2
  google_mobile_ads: 2.0.0
  google_sign_in: 5.2.4
  graphic: 0.6.2
  hainong_chat_call_module: 0.0.15
  http_parser: 4.0.0
  image_cropper: 3.0.3
  just_audio: 0.9.28
  local_auth: 2.1.6
  location: ^5.0.0
  number_paginator: ^0.3.2
  npk_core: 0.0.7+5
  package_info: ^2.0.2
  permission_handler: 10.2.0
  photo_manager_image_provider: ^1.1.1
  photo_view: ^0.14.0
  platform_device_id: 1.0.1
  qr_code_scanner: 1.0.1
  sentry_flutter: 6.18.0
  sign_in_with_apple: 4.3.0
  share: 2.0.0
  textfield_tags: ^3.0.1
  traceability_module: ^0.0.21
  trackasia_gl: 1.0.12
  video_compress: 3.1.1
  video_trimmer: 1.1.3
  webviewx: 0.2.1
  wechat_assets_picker: 8.3.2

dev_dependencies:
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/images/v2/
    - assets/images/v5/
    - assets/images/v7/
    - assets/images/v8/
    - assets/images/v9/
    - assets/images/v9/map/
    - assets/images/v9/map/weather/
    - assets/images/v9/map/pet/
    - assets/images/chatbot/
    - assets/videos/